### ISSUE TITLE
Can not use 3d carousel

### ISSUE THREAD

**Issue by peterwisu** [Wlada/vue-carousel-3d#209]
I followed the instruction in this site https://wlada.github.io/vue-carousel-3d/guide/ and got this error
 ```
Uncaught runtime errors:
×
ERROR
Cannot read properties of undefined (reading '_c')
TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.Carousel3dvue_type_template_id_07917306_scoped_true_render (webpack-internal:///./node_modules/vue-carousel-3d/dist/carousel-3d.common.js:3659:135)
    at renderComponentRoot (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:952:16)
    at ReactiveEffect.componentUpdateFn [as fn] (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5814:46)
    at ReactiveEffect.run (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:217:19)
    at instance.update (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5927:51)
    at setupRenderEffect (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5935:5)
    at mountComponent (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5725:5)
    at processComponent (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5678:9)
    at patch (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5166:11)
    at mountChildren (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5410:7)

```
Im using vue3js

**Comment by OOM-Softwares** [comment]
Did you find your way forward please ? I think it's not supported in Vue 3 js

**Comment by Wlada** [comment]
Resolved in v2.0.0 — the native Vue 3 build no longer uses `this._c`; please upgrade to `vue-carousel-3d@2`.
